In [1]:
from sklearn.datasets import load_iris
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score


In [2]:
data=load_iris()

In [3]:
cross_val_score(SVC(kernel="linear",C=10,gamma="scale"),data.data,data.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [19]:
cross_val_score(SVC(kernel="rbf",C=5,gamma="scale"),data.data,data.target,cv=5)

array([0.96666667, 1.        , 1.        , 0.96666667, 1.        ])

In [7]:
cross_val_score(SVC(kernel="poly",C=20,gamma="auto"),data.data,data.target,cv=5)

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [17]:
kernal=["poly","rbf","linear"]
C=[5,10,15,20,25,30]
gamma=["scale","auto"]
for i in kernal:
    for j in C:
        for k in gamma:
            out=cross_val_score(SVC(kernel=i,C=j,gamma=k),data.data,data.target,cv=5)
            print(f"kernal:{i},C={j},gamma={k}:{out.mean()}")

kernal:poly,C=5,gamma=scale:0.9666666666666666
kernal:poly,C=5,gamma=auto:0.9666666666666666
kernal:poly,C=10,gamma=scale:0.9666666666666666


kernal:poly,C=10,gamma=auto:0.9666666666666666
kernal:poly,C=15,gamma=scale:0.9666666666666666
kernal:poly,C=15,gamma=auto:0.96
kernal:poly,C=20,gamma=scale:0.9666666666666666
kernal:poly,C=20,gamma=auto:0.9533333333333334
kernal:poly,C=25,gamma=scale:0.9666666666666666
kernal:poly,C=25,gamma=auto:0.9533333333333334
kernal:poly,C=30,gamma=scale:0.9666666666666666
kernal:poly,C=30,gamma=auto:0.9533333333333334
kernal:rbf,C=5,gamma=scale:0.9866666666666667
kernal:rbf,C=5,gamma=auto:0.9800000000000001
kernal:rbf,C=10,gamma=scale:0.9800000000000001
kernal:rbf,C=10,gamma=auto:0.9800000000000001
kernal:rbf,C=15,gamma=scale:0.9800000000000001
kernal:rbf,C=15,gamma=auto:0.9733333333333334
kernal:rbf,C=20,gamma=scale:0.9800000000000001
kernal:rbf,C=20,gamma=auto:0.9666666666666668
kernal:rbf,C=25,gamma=scale:0.9800000000000001
kernal:rbf,C=25,gamma=auto:0.9666666666666668
kernal:rbf,C=30,gamma=scale:0.9733333333333334
kernal:rbf,C=30,gamma=auto:0.96
kernal:linear,C=5,gamma=scale:0.9800000000000

In [29]:
import pandas as pd

In [35]:
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(SVC(), {
    "kernel":["poly","rbf","linear"],
    "C":[i for i in range(1,11)],
    "gamma":["scale","auto"]
},cv=5,return_train_score=False)

clf.fit(data.data,data.target)
#df=pd.DataFrame(clf.cv_results_)
#df[["param_C","param_gamma","param_kernel","mean_test_score"]]

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['poly', 'rbf', 'linear']})

In [36]:
clf.best_score_

np.float64(0.9866666666666667)

In [37]:
clf.best_params_

{'C': 4, 'gamma': 'auto', 'kernel': 'rbf'}

In [34]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [63]:
model={
    "svm":{
        "model":SVC(),
        "params":{
            "kernel":["poly","rbf","linear"],
            "C":[i for i in range(1,11)],
            "gamma":["scale","auto"]
        }
    },
    "random_forest":{
        "model":RandomForestClassifier(),
        "params":{
            "n_estimators":[i for i in range(1,21)]
        }
    },
    "LogisticRegression":{
        "model":LogisticRegression(),
        "params":{
            "C":[i for i in range(1,11)],
        }
        }
}

In [50]:
model.items()

dict_items([('svm', {'model': SVC(), 'params': {'kernel': ['poly', 'rbf', 'linear'], 'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'gamma': ['scale', 'auto']}}), ('random_forest', {'model': RandomForestClassifier(), 'params': {'n_estimators': [1, 3, 5, 7, 9]}}), ('LogisticRegression', {'model': LogisticRegression(), 'params': {'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}})])

In [64]:
score={}
for m,mp in model.items():
    clf1=GridSearchCV(mp["model"],mp["params"],cv=5,return_train_score=False)
    clf1.fit(data.data,data.target)
    score[m]={"best_score":clf1.best_score_,
                "best_params":clf1.best_params_}

c:\Users\annad\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\annad\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

In [65]:
df1=pd.DataFrame(score)
df1.T

best_score                                 best_params
svm                  0.986667  {'C': 4, 'gamma': 'auto', 'kernel': 'rbf'}
random_forest        0.966667                         {'n_estimators': 6}
LogisticRegression       0.98                                   {'C': 10}

In [55]:
score

{'m': {'best_score': np.float64(0.9800000000000001), 'best_params': {'C': 10}}}